In [153]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [183]:
data=pd.read_csv("wholedata.csv")
data.head()
data.shape

(325, 33)

In [184]:
# data formatting
data=data.replace("-",np.nan)
data=data.replace("0",np.nan)
data=data.replace(">99",99)
data.head()

,country,RSA,rural water supply,urban water supply,ARA,Health,2018 EPI SCORE,Rural population (1000 inhab),Urban population (1000 inhab),Population density (inhab/km2)_x,...,Agricultural water withdrawal (10^9 m3/year),Industrial water withdrawal (km<sup>3</sup>/year or 10<sup>9</sup>m<sup>3</sup>/year),Municipal water withdrawal (km<sup>3</sup>/year or 10<sup>9</sup>m<sup>3</sup>/year),Total water withdrawal per capita (m<sup>3</sup>/year per inhabitant),MDG 7.5. Freshwater withdrawal as % of total renewable water resources (%),SDG 6.4.2. Water Stress (%),SDG 6.4.1. Water Use Efficiency (US$/m3)_y,Resilience and securityStorage,water productivity(industry),water productivity(Total agricultural production_US$)
0,Afghanistan,62.26143773,57.32129212,95.90874286,2.730664253,694.109542,37.74,26558.609,8971.472,55.595553,...,20.000,0.1695,0.2034,561.297018,31.045461,54.757019,0.923778,2.00900,1.022643,4.500000e+09
1,Albania,98.28801438,89.87517388,91.8354214,-0.265874296,2.511507,65.46,1190.155,1740.032,104.008979,...,0.905,0.2318,0.2830,492.273511,3.933775,7.139423,6.656907,4.03000,11.765478,2.310000e+09
2,Algeria,89.67236867,88.69095651,95.44293244,0.073382147,137.442788,57.18,11547.532,29770.610,17.377711,...,6.671,0.1910,3.6000,252.771321,84.014742,137.920360,14.354620,8.61925,20.235979,6.080000e+10
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,99,99,99,NaN,NaN,NaN,9.120,67.845,163.831915,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.560000e+08

In [185]:
data.dtypes

country                                                                                   object
RSA                                                                                       object
rural water supply                                                                        object
urban water supply                                                                        object
ARA                                                                                       object
Health                                                                                   float64
2018 EPI SCORE                                                                           float64
Rural population (1000 inhab)                                                            float64
Urban population (1000 inhab)                                                            float64
Population density (inhab/km2)_x                                                         float64
GDP per capita (current US$/inhab)                                                       float64
Human Development Index (HDI) [highest = 1] (-)                                          float64
Groundwater: accounted outflow to other countries (10^9 m3/year)                         float64
Produced municipal wastewater (km<sup>3</sup>/year or 10^9m<sup>3</sup>/year)            float64
Collected municipal wastewater (km<sup>3</sup>/year or 10^9m<sup>3</sup>/year)           float64
Treated municipal wastewater (km<sup>3</sup>/year or 10^9m<sup>3</sup>/year)             float64
Number of municipal wastewater treatment facilities (-)                                  float64
Capacity of the municipal wastewater treatment facilities (10^9 m3/yr)                   float64
SDG 6.4.1. Water Use Efficiency (US$/m3)_x                                               float64
Non-irrigated cultivated area drained (1000 ha)                                          float64
Flood occurrence (WRI) (-)                                                               float64
Population affected by water related disease (1000 inhabitants)                          float64
Total renewable water resources per capita (m3/inhab/yr)                                 float64
Agricultural water withdrawal (10^9 m3/year)                                             float64
Industrial water withdrawal (km<sup>3</sup>/year or 10<sup>9</sup>m<sup>3</sup>/year)    float64
Municipal water withdrawal (km<sup>3</sup>/year or 10<sup>9</sup>m<sup>3</sup>/year)     float64
Total water withdrawal per capita (m<sup>3</sup>/year per inhabitant)                    float64
MDG 7.5. Freshwater withdrawal as % of total renewable water resources (%)               float64
SDG 6.4.2. Water Stress (%)                                                              float64
SDG 6.4.1. Water Use Efficiency (US$/m3)_y                                               float64
Resilience and securityStorage                                                           float64
water productivity(industry)                                                             float64
water productivity(Total agricultural production_US$)                                    float64
dtype: object

In [186]:

# 转换数据类型
#data["rural water supply"]=data["rural water supply"].astype(float)
#data["urban water supply"]=data["urban water supply"].astype(float)
#data["water security index"]=data["water security index"].astype(float)
#data["RSA"]=data["RSA"].astype(float)
#data["Annual rate of change "]=data["Annual rate of change "].astype(float)

df_missing=data.isnull().sum().reset_index()
df_missing.columns=["feature","missing count"]
df_missing["missing percentage"]=df_missing["missing count"]/data.shape[0]
#df_missing["missing percentage"]=df_missing["missing percentage"].map(lambda x:"{:0.2%}".format(x))
df_missing.sort_values(by="missing count",ascending=True,inplace=True)
df_missing

,feature,missing count,missing percentage
0,country,0,0.000000
31,water productivity(industry),114,0.350769
8,Urban population (1000 inhab),125,0.384615
7,Rural population (1000 inhab),125,0.384615
9,Population density (inhab/km2)_x,127,0.390769
22,Total renewable water resources per capita (m3...,128,0.393846
10,GDP per capita (current US$/inhab),129,0.396923
32,water productivity(Total agricultural producti...,129,0.396923
11,Human Development Index (HDI) [highest = 1] (-),137,0.421538
5,Health,142,0.436923
25,Municipal water withdrawal (km<sup>3</sup>/yea...,142,0.436923
26,Total water withdrawal per capita (m<sup>3</su...,145,0.446154
24,Industrial water withdrawal (km<sup>3</sup>/ye...,145,0.446154
23,Agricultural water withdrawal (10^9 m3/year),145,0.446154
6,2018 EPI SCORE,145,0.446154
28,SDG 6.4.2. Water Stress (%),147,0.452308
27,MDG 7.5. Freshwater withdrawal as % of total r...,147,0.452308
20,Flood occurrence (WRI) (-),149,0.458462
3,urban water supply,150,0.461538
1,RSA,152,0.467692
18,SDG 6.4.1. Water Use Efficiency (US$/m3)_x,157,0.483077
2,rural water supply,157,0.483077
29,SDG 6.4.1. Water Use Efficiency (US$/m3)_y,157,0.483077
30,Resilience and securityStorage,161,0.495385
12,Groundwater: accounted outflow to other countr...,170,0.523077
4,ARA,183,0.563077
13,Produced municipal wastewater (km<sup>3</sup>/...,198,0.609231
15,Treated municipal wastewater (km<sup>3</sup>/y...,212,0.652308
16,Number of municipal wastewater treatment facil...,242,0.744615
14,Collected municipal wastewater (km<sup>3</sup>...,259,0.796923
17,Capacity of the municipal wastewater treatment...,267,0.821538
19,Non-irrigated cultivated area drained (1000 ha),283,0.870769
21,Population affected by water related disease (...,293,0.901538

In [188]:
#More missing data than Asia data, so 0.35 change to 0.65
df=df_missing[df_missing["missing percentage"]<0.65]
df
data=data[df["feature"]]
data.head()

,country,water productivity(industry),Urban population (1000 inhab),Rural population (1000 inhab),Population density (inhab/km2)_x,Total renewable water resources per capita (m3/inhab/yr),GDP per capita (current US$/inhab),water productivity(Total agricultural production_US$),Human Development Index (HDI) [highest = 1] (-),Health,...,Flood occurrence (WRI) (-),urban water supply,RSA,SDG 6.4.1. Water Use Efficiency (US$/m3)_x,rural water supply,SDG 6.4.1. Water Use Efficiency (US$/m3)_y,Resilience and securityStorage,Groundwater: accounted outflow to other countries (10^9 m3/year),ARA,Produced municipal wastewater (km<sup>3</sup>/year or 10^9m<sup>3</sup>/year)
0,Afghanistan,1.022643,8971.472,26558.609,55.595553,1799.917253,605.557362,4.500000e+09,0.493,694.109542,...,3.7,95.90874286,62.26143773,0.923778,57.32129212,0.923778,2.00900,NaN,2.730664253,NaN
1,Albania,11.765478,1740.032,1190.155,104.008979,10470.953680,4445.132198,2.310000e+09,0.789,2.511507,...,2.7,91.8354214,98.28801438,6.656907,89.87517388,6.656907,4.03000,0.0,-0.265874296,0.054
2,Algeria,20.235979,29770.610,11547.532,17.377711,281.885204,4051.244377,6.080000e+10,0.758,137.442788,...,2.8,95.44293244,89.67236867,14.354620,88.69095651,14.354620,8.61925,0.1,0.073382147,1.500
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,NaN,67.845,9.120,163.831915,4098.648070,39249.689020,2.560000e+08,0.852,NaN,...,3.3,99,99,NaN,99,NaN,NaN,NaN,NaN,NaN

In [189]:
#data.to_csv("Ratesmalerthan35.csv",encoding="utf-8")
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)

In [191]:
listcolumn=data.columns
data_new=imputer.fit_transform(data[listcolumn[1:]])
data_new=pd.DataFrame(data_new)
data_new.columns=listcolumn[1:]
data_new.insert(0,"country",data["country"])
data_new
#data_new.to_csv("Imputed.csv",encoding="utf-8")

,country,water productivity(industry),Urban population (1000 inhab),Rural population (1000 inhab),Population density (inhab/km2)_x,Total renewable water resources per capita (m3/inhab/yr),GDP per capita (current US$/inhab),water productivity(Total agricultural production_US$),Human Development Index (HDI) [highest = 1] (-),Health,...,Flood occurrence (WRI) (-),urban water supply,RSA,SDG 6.4.1. Water Use Efficiency (US$/m3)_x,rural water supply,SDG 6.4.1. Water Use Efficiency (US$/m3)_y,Resilience and securityStorage,Groundwater: accounted outflow to other countries (10^9 m3/year),ARA,Produced municipal wastewater (km<sup>3</sup>/year or 10^9m<sup>3</sup>/year)
0,Afghanistan,1.022643,8971.47200,26558.609000,55.595553,1799.917253,605.557362,4.500000e+09,0.493000,694.109542,...,3.700000,95.908743,62.261438,0.923778,57.321292,0.923778,2.009000,0.000000,2.730664,0.116600
1,Albania,11.765478,1740.03200,1190.155000,104.008979,10470.953680,4445.132198,2.310000e+09,0.789000,2.511507,...,2.700000,91.835421,98.288014,6.656907,89.875174,6.656907,4.030000,0.000000,-0.265874,0.054000
2,Algeria,20.235979,29770.61000,11547.532000,17.377711,281.885204,4051.244377,6.080000e+10,0.758000,137.442788,...,2.800000,95.442932,89.672369,14.354620,88.690957,14.354620,8.619250,0.100000,0.073382,1.500000
3,American Samoa,75.500347,20681.74333,17046.340835,195.664495,17226.600056,14951.892850,1.012615e+11,0.710021,571.311294,...,2.695455,94.158222,79.679500,46.862185,80.515798,46.862185,43.399025,0.266458,0.230218,61.178619
4,Andorra,113.577426,67.84500,9.120000,163.831915,4098.648070,39249.689020,2.560000e+08,0.852000,25.539652,...,3.300000,99.000000,99.000000,38.590905,99.000000,38.590905,0.117064,0.000000,0.090283,0.005880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,Virgin Islands (U.S.),75.500347,20681.74333,17046.340835,195.664495,17226.600056,14951.892850,1.012615e+11,0.710021,571.311294,...,2.695455,94.158222,79.679500,46.862185,80.515798,46.862185,43.399025,0.266458,0.230218,61.178619
321,Vietnam,2.141214,9081.02200,5435.441800,63.071263,9358.272748,2014.239357,4.712600e+09,0.807600,484.405530,...,2.300000,94.776894,74.723468,17.178177,70.380832,17.178177,26.198266,0.006000,0.931179,0.935760
322,World,20.611415,5850.78560,6049.221400,51.422622,7976.340722,4116.933947,2.691800e+10,0.679800,170.589206,...,2.200000,96.725155,85.208220,7.711055,66.477410,7.711055,21.469621,0.006000,0.745904,0.903040
323,Kosovo,75.500347,20681.74333,17046.340835,195.664495,17226.600056,14951.892850,1.012615e+11,0.710021,571.311294,...,2.695455,94.158222,79.679500,46.862185,80.515798,46.862185,43.399025,0.266458,0.230218,61.178619
324,"Yemen, Rep.",5.021698,9081.02200,5435.441800,63.071263,9358.272748,2014.239357,4.712600e+09,0.807600,484.405530,...,2.300000,92.161550,80.974228,17.178177,70.380832,17.178177,26.198266,0.006000,0.612012,0.935760

In [192]:
# Normalization

# remove the column of country name & water securty index
country_name = data_new.iloc[:,0]  #get the content of country name column

norm_data = data_new.drop('country',axis=1,inplace=False)
# print(norm_data_asia.dtypes)

#normalization
norm_df = norm_data.apply(lambda x: (x - np.min(x)) / (np.max(x) - np.min(x)))
#print(norm_asia.head(5))

#add the column of country name
norm_df.insert(0,'country',country_name)
#print(norm_df.head(5))


# 2. min-max, SKL

# create a scaler object
#scaler2 = MinMaxScaler()
# fit and transform the data
#asia_norm = pd.DataFrame(scaler.fit_transform(df_cars), columns=df_cars.columns)



# output the preprocessed dataframe
norm_df.to_csv('average whole.csv')